# Generated by Django 2.1.7 on 2019-05-07 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateField()),
                ('quantidade', models.IntegerField()),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Prato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PF', 'PF'), ('Quentinha', 'Quentinha'), ('Comercial', 'Comercial')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='prato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.Prato'),
        ),
    ]
