# Generated by Django 2.1.7 on 2019-05-07 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='descricao',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
