# Generated by Django 2.1.7 on 2019-05-07 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_pedido_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='prato',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
