# Generated by Django 2.1.7 on 2019-05-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0004_pedido_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='prato',
        ),
        migrations.AddField(
            model_name='pedido',
            name='prato',
            field=models.ManyToManyField(to='pedido.Prato'),
        ),
    ]
