# Generated by Django 2.1.7 on 2019-05-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0005_auto_20190507_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data_pedido',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='prato',
            name='tipo',
            field=models.CharField(choices=[('PF', 'PF'), ('Quentinha', 'Quentinha'), ('Comercial', 'Comercial'), ('Suco', 'Suco'), ('Refrigerante', 'Refrigerante'), ('Serveja', 'Serveja')], max_length=50),
        ),
    ]
