# Generated by Django 2.1.7 on 2019-05-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0006_auto_20190514_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='carne',
            field=models.CharField(choices=[('Boi', 'Boi'), ('Frango', 'Frango'), ('Porco', 'Porco'), ('Picadinho', 'Picadinho')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_pedido',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
